CREATE DATABASE QuanLyBanHang;
USE QuanLyBanHang;
CREATE TABLE Customer
(
    cID   INT AUTO_INCREMENT PRIMARY KEY,
    cName VARCHAR(60) NOT NULL,
    cAge INT NOT NULL,
);
CREATE TABLE Order
(
    oID   INT AUTO_INCREMENT PRIMARY KEY,
    cID INT FORGEIN KEY REFERENCES Customer(cID),
    oDate DATE NOT NULL,
    oTotalPrice DOUBLE NOT NULL
);
CREATE TABLE Product
(
    pID INT AUTO_INCREMENT PRIMARY KEY,
    pName varchar(60),
    pPrice DOUBLE NOT NULL
);
CREATE TABLE OrderDetai;l
(
    oID INT,
    pID INT,
    odQTY INT NOT NULL,
    PRIMARY KEY(oID,pID),
);